// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from "@hey-api/client-axios"
import {
  queryOptions,
  type UseMutationOptions,
  type DefaultError,
} from "@tanstack/react-query"
import type {
  LoginAccessTokenData,
  LoginAccessTokenError,
  LoginAccessTokenResponse,
  TestTokenData,
  TestTokenResponse,
  RecoverPasswordData,
  RecoverPasswordError,
  RecoverPasswordResponse,
  ResetPasswordData,
  ResetPasswordError,
  ResetPasswordResponse,
  RecoverPasswordHtmlContentData,
  RecoverPasswordHtmlContentError,
  RecoverPasswordHtmlContentResponse,
  ReadUsersData,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  DeleteUserMeData,
  DeleteUserMeResponse,
  ReadUserMeData,
  UpdateUserMeData,
  UpdateUserMeError,
  UpdateUserMeResponse,
  UpdatePasswordMeData,
  UpdatePasswordMeError,
  UpdatePasswordMeResponse,
  RegisterUserData,
  RegisterUserError,
  RegisterUserResponse,
  ActivateAccountData,
  DeleteUserData,
  DeleteUserError,
  DeleteUserResponse,
  ReadUserByIdData,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
  TestEmailData,
  TestEmailError,
  TestEmailResponse,
  HealthCheckData,
  MaxUploadSizeData,
  ReadToolsData,
  CreateToolData,
  CreateToolError,
  CreateToolResponse,
  ReadToolByNameData,
  DeleteToolData,
  DeleteToolError,
  DeleteToolResponse,
  ReadToolData,
  UpdateToolData,
  UpdateToolError,
  UpdateToolResponse,
  UnfavouriteToolData,
  UnfavouriteToolError,
  UnfavouriteToolResponse,
  FavouriteToolData,
  FavouriteToolError,
  FavouriteToolResponse,
  EnableToolData,
  EnableToolError,
  EnableToolResponse,
  DisableToolData,
  DisableToolError,
  DisableToolResponse,
  EnableLlmSummaryData,
  EnableLlmSummaryError,
  EnableLlmSummaryResponse,
  DisableLlmSummaryData,
  DisableLlmSummaryError,
  DisableLlmSummaryResponse,
  InstallToolData,
  InstallToolError,
  InstallToolResponse,
  UninstallToolData,
  UninstallToolError,
  UninstallToolResponse,
  DeleteFilesData,
  ReadFilesData,
  UploadFileData,
  UploadFileError,
  UploadFileResponse,
  GetFilesAllowedTypesData,
  GetFilesStatsData,
  CreatePairData,
  CreatePairError,
  CreatePairResponse,
  DeleteFileData,
  DeleteFileError,
  ReadFileData,
  SaveFileData,
  SaveFileError,
  SaveFileResponse,
  DownloadFileData,
  GetDownloadTokenData,
  DownloadFileWithTokenData,
  DeleteRunsData,
  DeleteRunsResponse,
  ReadRunsData,
  CreateRunData,
  CreateRunError,
  CreateRunResponse,
  CancelRunsData,
  CancelRunsResponse,
  ReadActiveRunsData,
  DeleteRunData,
  DeleteRunError,
  DeleteRunResponse,
  ReadRunData,
  CancelRunData,
  CancelRunError,
  CancelRunResponse,
  RenameRunData,
  RenameRunError,
  RenameRunResponse,
  GenerateRunSummaryData,
  GenerateRunSummaryError,
  GenerateRunSummaryResponse,
} from "../types.gen"
import type { AxiosError } from "axios"
import {
  LoginService,
  UsersService,
  UtilsService,
  ToolsService,
  FilesService,
  RunsService,
  LlmService,
  client,
} from "../sdk.gen"

type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return params
}

export const loginAccessTokenQueryKey = (
  options: Options<LoginAccessTokenData>,
) => [createQueryKey("loginAccessToken", options)]

export const loginAccessTokenOptions = (
  options: Options<LoginAccessTokenData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await LoginService.loginAccessToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: loginAccessTokenQueryKey(options),
  })
}

export const loginAccessTokenMutation = (
  options?: Partial<Options<LoginAccessTokenData>>,
) => {
  const mutationOptions: UseMutationOptions<
    LoginAccessTokenResponse,
    AxiosError<LoginAccessTokenError>,
    Options<LoginAccessTokenData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await LoginService.loginAccessToken({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const testTokenQueryKey = (options?: Options<TestTokenData>) => [
  createQueryKey("testToken", options),
]

export const testTokenOptions = (options?: Options<TestTokenData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await LoginService.testToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: testTokenQueryKey(options),
  })
}

export const testTokenMutation = (
  options?: Partial<Options<TestTokenData>>,
) => {
  const mutationOptions: UseMutationOptions<
    TestTokenResponse,
    AxiosError<DefaultError>,
    Options<TestTokenData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await LoginService.testToken({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const recoverPasswordQueryKey = (
  options: Options<RecoverPasswordData>,
) => [createQueryKey("recoverPassword", options)]

export const recoverPasswordOptions = (
  options: Options<RecoverPasswordData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await LoginService.recoverPassword({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: recoverPasswordQueryKey(options),
  })
}

export const recoverPasswordMutation = (
  options?: Partial<Options<RecoverPasswordData>>,
) => {
  const mutationOptions: UseMutationOptions<
    RecoverPasswordResponse,
    AxiosError<RecoverPasswordError>,
    Options<RecoverPasswordData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await LoginService.recoverPassword({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const resetPasswordQueryKey = (options: Options<ResetPasswordData>) => [
  createQueryKey("resetPassword", options),
]

export const resetPasswordOptions = (options: Options<ResetPasswordData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await LoginService.resetPassword({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: resetPasswordQueryKey(options),
  })
}

export const resetPasswordMutation = (
  options?: Partial<Options<ResetPasswordData>>,
) => {
  const mutationOptions: UseMutationOptions<
    ResetPasswordResponse,
    AxiosError<ResetPasswordError>,
    Options<ResetPasswordData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await LoginService.resetPassword({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const recoverPasswordHtmlContentQueryKey = (
  options: Options<RecoverPasswordHtmlContentData>,
) => [createQueryKey("recoverPasswordHtmlContent", options)]

export const recoverPasswordHtmlContentOptions = (
  options: Options<RecoverPasswordHtmlContentData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await LoginService.recoverPasswordHtmlContent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: recoverPasswordHtmlContentQueryKey(options),
  })
}

export const recoverPasswordHtmlContentMutation = (
  options?: Partial<Options<RecoverPasswordHtmlContentData>>,
) => {
  const mutationOptions: UseMutationOptions<
    RecoverPasswordHtmlContentResponse,
    AxiosError<RecoverPasswordHtmlContentError>,
    Options<RecoverPasswordHtmlContentData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await LoginService.recoverPasswordHtmlContent({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readUsersQueryKey = (options?: Options<ReadUsersData>) => [
  createQueryKey("readUsers", options),
]

export const readUsersOptions = (options?: Options<ReadUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await UsersService.readUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readUsersQueryKey(options),
  })
}

export const createUserQueryKey = (options: Options<CreateUserData>) => [
  createQueryKey("createUser", options),
]

export const createUserOptions = (options: Options<CreateUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await UsersService.createUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createUserQueryKey(options),
  })
}

export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CreateUserResponse,
    AxiosError<CreateUserError>,
    Options<CreateUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await UsersService.createUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const deleteUserMeMutation = (
  options?: Partial<Options<DeleteUserMeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    DeleteUserMeResponse,
    AxiosError<DefaultError>,
    Options<DeleteUserMeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await UsersService.deleteUserMe({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readUserMeQueryKey = (options?: Options<ReadUserMeData>) => [
  createQueryKey("readUserMe", options),
]

export const readUserMeOptions = (options?: Options<ReadUserMeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await UsersService.readUserMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readUserMeQueryKey(options),
  })
}

export const updateUserMeMutation = (
  options?: Partial<Options<UpdateUserMeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UpdateUserMeResponse,
    AxiosError<UpdateUserMeError>,
    Options<UpdateUserMeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await UsersService.updateUserMe({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const updatePasswordMeMutation = (
  options?: Partial<Options<UpdatePasswordMeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UpdatePasswordMeResponse,
    AxiosError<UpdatePasswordMeError>,
    Options<UpdatePasswordMeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await UsersService.updatePasswordMe({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const registerUserQueryKey = (options: Options<RegisterUserData>) => [
  createQueryKey("registerUser", options),
]

export const registerUserOptions = (options: Options<RegisterUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await UsersService.registerUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: registerUserQueryKey(options),
  })
}

export const registerUserMutation = (
  options?: Partial<Options<RegisterUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    RegisterUserResponse,
    AxiosError<RegisterUserError>,
    Options<RegisterUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await UsersService.registerUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const activateAccountQueryKey = (
  options: Options<ActivateAccountData>,
) => [createQueryKey("activateAccount", options)]

export const activateAccountOptions = (
  options: Options<ActivateAccountData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await UsersService.activateAccount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: activateAccountQueryKey(options),
  })
}

export const deleteUserMutation = (
  options?: Partial<Options<DeleteUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    DeleteUserResponse,
    AxiosError<DeleteUserError>,
    Options<DeleteUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await UsersService.deleteUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readUserByIdQueryKey = (options: Options<ReadUserByIdData>) => [
  createQueryKey("readUserById", options),
]

export const readUserByIdOptions = (options: Options<ReadUserByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await UsersService.readUserById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readUserByIdQueryKey(options),
  })
}

export const updateUserMutation = (
  options?: Partial<Options<UpdateUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UpdateUserResponse,
    AxiosError<UpdateUserError>,
    Options<UpdateUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await UsersService.updateUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const testEmailQueryKey = (options: Options<TestEmailData>) => [
  createQueryKey("testEmail", options),
]

export const testEmailOptions = (options: Options<TestEmailData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await UtilsService.testEmail({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: testEmailQueryKey(options),
  })
}

export const testEmailMutation = (
  options?: Partial<Options<TestEmailData>>,
) => {
  const mutationOptions: UseMutationOptions<
    TestEmailResponse,
    AxiosError<TestEmailError>,
    Options<TestEmailData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await UtilsService.testEmail({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const healthCheckQueryKey = (options?: Options<HealthCheckData>) => [
  createQueryKey("healthCheck", options),
]

export const healthCheckOptions = (options?: Options<HealthCheckData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await UtilsService.healthCheck({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: healthCheckQueryKey(options),
  })
}

export const maxUploadSizeQueryKey = (options?: Options<MaxUploadSizeData>) => [
  createQueryKey("maxUploadSize", options),
]

export const maxUploadSizeOptions = (options?: Options<MaxUploadSizeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await UtilsService.maxUploadSize({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: maxUploadSizeQueryKey(options),
  })
}

export const readToolsQueryKey = (options?: Options<ReadToolsData>) => [
  createQueryKey("readTools", options),
]

export const readToolsOptions = (options?: Options<ReadToolsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.readTools({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readToolsQueryKey(options),
  })
}

export const createToolQueryKey = (options: Options<CreateToolData>) => [
  createQueryKey("createTool", options),
]

export const createToolOptions = (options: Options<CreateToolData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.createTool({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createToolQueryKey(options),
  })
}

export const createToolMutation = (
  options?: Partial<Options<CreateToolData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CreateToolResponse,
    AxiosError<CreateToolError>,
    Options<CreateToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.createTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readToolByNameQueryKey = (
  options: Options<ReadToolByNameData>,
) => [createQueryKey("readToolByName", options)]

export const readToolByNameOptions = (options: Options<ReadToolByNameData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.readToolByName({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readToolByNameQueryKey(options),
  })
}

export const deleteToolMutation = (
  options?: Partial<Options<DeleteToolData>>,
) => {
  const mutationOptions: UseMutationOptions<
    DeleteToolResponse,
    AxiosError<DeleteToolError>,
    Options<DeleteToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.deleteTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readToolQueryKey = (options: Options<ReadToolData>) => [
  createQueryKey("readTool", options),
]

export const readToolOptions = (options: Options<ReadToolData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.readTool({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readToolQueryKey(options),
  })
}

export const updateToolMutation = (
  options?: Partial<Options<UpdateToolData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UpdateToolResponse,
    AxiosError<UpdateToolError>,
    Options<UpdateToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.updateTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const unfavouriteToolMutation = (
  options?: Partial<Options<UnfavouriteToolData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UnfavouriteToolResponse,
    AxiosError<UnfavouriteToolError>,
    Options<UnfavouriteToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.unfavouriteTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const favouriteToolQueryKey = (options: Options<FavouriteToolData>) => [
  createQueryKey("favouriteTool", options),
]

export const favouriteToolOptions = (options: Options<FavouriteToolData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.favouriteTool({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: favouriteToolQueryKey(options),
  })
}

export const favouriteToolMutation = (
  options?: Partial<Options<FavouriteToolData>>,
) => {
  const mutationOptions: UseMutationOptions<
    FavouriteToolResponse,
    AxiosError<FavouriteToolError>,
    Options<FavouriteToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.favouriteTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const enableToolQueryKey = (options: Options<EnableToolData>) => [
  createQueryKey("enableTool", options),
]

export const enableToolOptions = (options: Options<EnableToolData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.enableTool({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: enableToolQueryKey(options),
  })
}

export const enableToolMutation = (
  options?: Partial<Options<EnableToolData>>,
) => {
  const mutationOptions: UseMutationOptions<
    EnableToolResponse,
    AxiosError<EnableToolError>,
    Options<EnableToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.enableTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const disableToolQueryKey = (options: Options<DisableToolData>) => [
  createQueryKey("disableTool", options),
]

export const disableToolOptions = (options: Options<DisableToolData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.disableTool({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: disableToolQueryKey(options),
  })
}

export const disableToolMutation = (
  options?: Partial<Options<DisableToolData>>,
) => {
  const mutationOptions: UseMutationOptions<
    DisableToolResponse,
    AxiosError<DisableToolError>,
    Options<DisableToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.disableTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const enableLlmSummaryQueryKey = (
  options: Options<EnableLlmSummaryData>,
) => [createQueryKey("enableLlmSummary", options)]

export const enableLlmSummaryOptions = (
  options: Options<EnableLlmSummaryData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.enableLlmSummary({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: enableLlmSummaryQueryKey(options),
  })
}

export const enableLlmSummaryMutation = (
  options?: Partial<Options<EnableLlmSummaryData>>,
) => {
  const mutationOptions: UseMutationOptions<
    EnableLlmSummaryResponse,
    AxiosError<EnableLlmSummaryError>,
    Options<EnableLlmSummaryData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.enableLlmSummary({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const disableLlmSummaryQueryKey = (
  options: Options<DisableLlmSummaryData>,
) => [createQueryKey("disableLlmSummary", options)]

export const disableLlmSummaryOptions = (
  options: Options<DisableLlmSummaryData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.disableLlmSummary({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: disableLlmSummaryQueryKey(options),
  })
}

export const disableLlmSummaryMutation = (
  options?: Partial<Options<DisableLlmSummaryData>>,
) => {
  const mutationOptions: UseMutationOptions<
    DisableLlmSummaryResponse,
    AxiosError<DisableLlmSummaryError>,
    Options<DisableLlmSummaryData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.disableLlmSummary({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const installToolQueryKey = (options: Options<InstallToolData>) => [
  createQueryKey("installTool", options),
]

export const installToolOptions = (options: Options<InstallToolData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ToolsService.installTool({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: installToolQueryKey(options),
  })
}

export const installToolMutation = (
  options?: Partial<Options<InstallToolData>>,
) => {
  const mutationOptions: UseMutationOptions<
    InstallToolResponse,
    AxiosError<InstallToolError>,
    Options<InstallToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.installTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const uninstallToolMutation = (
  options?: Partial<Options<UninstallToolData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UninstallToolResponse,
    AxiosError<UninstallToolError>,
    Options<UninstallToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await ToolsService.uninstallTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const deleteFilesMutation = (
  options?: Partial<Options<DeleteFilesData>>,
) => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<DeleteFilesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await FilesService.deleteFiles({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readFilesQueryKey = (options?: Options<ReadFilesData>) => [
  createQueryKey("readFiles", options),
]

export const readFilesOptions = (options?: Options<ReadFilesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.readFiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readFilesQueryKey(options),
  })
}

export const uploadFileQueryKey = (options: Options<UploadFileData>) => [
  createQueryKey("uploadFile", options),
]

export const uploadFileOptions = (options: Options<UploadFileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.uploadFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: uploadFileQueryKey(options),
  })
}

export const uploadFileMutation = (
  options?: Partial<Options<UploadFileData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UploadFileResponse,
    AxiosError<UploadFileError>,
    Options<UploadFileData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await FilesService.uploadFile({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getFilesAllowedTypesQueryKey = (
  options?: Options<GetFilesAllowedTypesData>,
) => [createQueryKey("getFilesAllowedTypes", options)]

export const getFilesAllowedTypesOptions = (
  options?: Options<GetFilesAllowedTypesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.getFilesAllowedTypes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getFilesAllowedTypesQueryKey(options),
  })
}

export const getFilesStatsQueryKey = (options?: Options<GetFilesStatsData>) => [
  createQueryKey("getFilesStats", options),
]

export const getFilesStatsOptions = (options?: Options<GetFilesStatsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.getFilesStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getFilesStatsQueryKey(options),
  })
}

export const createPairQueryKey = (options: Options<CreatePairData>) => [
  createQueryKey("createPair", options),
]

export const createPairOptions = (options: Options<CreatePairData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.createPair({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createPairQueryKey(options),
  })
}

export const createPairMutation = (
  options?: Partial<Options<CreatePairData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CreatePairResponse,
    AxiosError<CreatePairError>,
    Options<CreatePairData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await FilesService.createPair({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const deleteFileMutation = (
  options?: Partial<Options<DeleteFileData>>,
) => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DeleteFileError>,
    Options<DeleteFileData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await FilesService.deleteFile({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readFileQueryKey = (options: Options<ReadFileData>) => [
  createQueryKey("readFile", options),
]

export const readFileOptions = (options: Options<ReadFileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.readFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readFileQueryKey(options),
  })
}

export const saveFileQueryKey = (options: Options<SaveFileData>) => [
  createQueryKey("saveFile", options),
]

export const saveFileOptions = (options: Options<SaveFileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.saveFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: saveFileQueryKey(options),
  })
}

export const saveFileMutation = (options?: Partial<Options<SaveFileData>>) => {
  const mutationOptions: UseMutationOptions<
    SaveFileResponse,
    AxiosError<SaveFileError>,
    Options<SaveFileData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await FilesService.saveFile({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const downloadFileQueryKey = (options: Options<DownloadFileData>) => [
  createQueryKey("downloadFile", options),
]

export const downloadFileOptions = (options: Options<DownloadFileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.downloadFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: downloadFileQueryKey(options),
  })
}

export const getDownloadTokenQueryKey = (
  options: Options<GetDownloadTokenData>,
) => [createQueryKey("getDownloadToken", options)]

export const getDownloadTokenOptions = (
  options: Options<GetDownloadTokenData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.getDownloadToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getDownloadTokenQueryKey(options),
  })
}

export const downloadFileWithTokenQueryKey = (
  options: Options<DownloadFileWithTokenData>,
) => [createQueryKey("downloadFileWithToken", options)]

export const downloadFileWithTokenOptions = (
  options: Options<DownloadFileWithTokenData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await FilesService.downloadFileWithToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: downloadFileWithTokenQueryKey(options),
  })
}

export const deleteRunsMutation = (
  options?: Partial<Options<DeleteRunsData>>,
) => {
  const mutationOptions: UseMutationOptions<
    DeleteRunsResponse,
    AxiosError<DefaultError>,
    Options<DeleteRunsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await RunsService.deleteRuns({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readRunsQueryKey = (options?: Options<ReadRunsData>) => [
  createQueryKey("readRuns", options),
]

export const readRunsOptions = (options?: Options<ReadRunsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await RunsService.readRuns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readRunsQueryKey(options),
  })
}

export const createRunQueryKey = (options: Options<CreateRunData>) => [
  createQueryKey("createRun", options),
]

export const createRunOptions = (options: Options<CreateRunData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await RunsService.createRun({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createRunQueryKey(options),
  })
}

export const createRunMutation = (
  options?: Partial<Options<CreateRunData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CreateRunResponse,
    AxiosError<CreateRunError>,
    Options<CreateRunData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await RunsService.createRun({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const cancelRunsMutation = (
  options?: Partial<Options<CancelRunsData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CancelRunsResponse,
    AxiosError<DefaultError>,
    Options<CancelRunsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await RunsService.cancelRuns({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readActiveRunsQueryKey = (
  options?: Options<ReadActiveRunsData>,
) => [createQueryKey("readActiveRuns", options)]

export const readActiveRunsOptions = (
  options?: Options<ReadActiveRunsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await RunsService.readActiveRuns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readActiveRunsQueryKey(options),
  })
}

export const deleteRunMutation = (
  options?: Partial<Options<DeleteRunData>>,
) => {
  const mutationOptions: UseMutationOptions<
    DeleteRunResponse,
    AxiosError<DeleteRunError>,
    Options<DeleteRunData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await RunsService.deleteRun({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const readRunQueryKey = (options: Options<ReadRunData>) => [
  createQueryKey("readRun", options),
]

export const readRunOptions = (options: Options<ReadRunData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await RunsService.readRun({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readRunQueryKey(options),
  })
}

export const cancelRunMutation = (
  options?: Partial<Options<CancelRunData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CancelRunResponse,
    AxiosError<CancelRunError>,
    Options<CancelRunData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await RunsService.cancelRun({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const renameRunMutation = (
  options?: Partial<Options<RenameRunData>>,
) => {
  const mutationOptions: UseMutationOptions<
    RenameRunResponse,
    AxiosError<RenameRunError>,
    Options<RenameRunData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await RunsService.renameRun({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const generateRunSummaryQueryKey = (
  options: Options<GenerateRunSummaryData>,
) => [createQueryKey("generateRunSummary", options)]

export const generateRunSummaryOptions = (
  options: Options<GenerateRunSummaryData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await LlmService.generateRunSummary({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: generateRunSummaryQueryKey(options),
  })
}

export const generateRunSummaryMutation = (
  options?: Partial<Options<GenerateRunSummaryData>>,
) => {
  const mutationOptions: UseMutationOptions<
    GenerateRunSummaryResponse,
    AxiosError<GenerateRunSummaryError>,
    Options<GenerateRunSummaryData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await LlmService.generateRunSummary({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
