// This file is auto-generated by @hey-api/openapi-ts

export const AudienceSchema = {
    type: 'string',
    enum: ['layman', 'expert'],
    title: 'Audience'
} as const;

export const Body_files_upload_fileSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_files-upload_file'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_runs_create_runSchema = {
    properties: {
        params: {
            additionalProperties: true,
            type: 'object',
            title: 'Params'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        }
    },
    type: 'object',
    required: ['params'],
    title: 'Body_runs-create_run'
} as const;

export const CondaEnvSchema = {
    properties: {
        channels: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Channels'
        },
        dependencies: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        '$ref': '#/components/schemas/CondaEnvPipDependency'
                    }
                ]
            },
            type: 'array',
            title: 'Dependencies'
        }
    },
    type: 'object',
    title: 'CondaEnv'
} as const;

export const CondaEnvPipDependencySchema = {
    properties: {
        pip: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Pip'
        }
    },
    type: 'object',
    required: ['pip'],
    title: 'CondaEnvPipDependency'
} as const;

export const FilePublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        file_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Type'
        },
        size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        saved: {
            type: 'boolean',
            title: 'Saved',
            default: false
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        is_group: {
            type: 'boolean',
            title: 'Is Group',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        children: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/FilePublicChild'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Children'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at'],
    title: 'FilePublic'
} as const;

export const FilePublicChildSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        file_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Type'
        },
        size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        saved: {
            type: 'boolean',
            title: 'Saved',
            default: false
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        is_group: {
            type: 'boolean',
            title: 'Is Group',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        run_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Run Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at'],
    title: 'FilePublicChild'
} as const;

export const FileStatsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        saved: {
            type: 'integer',
            title: 'Saved'
        },
        temporary: {
            type: 'integer',
            title: 'Temporary'
        },
        total_size_bytes: {
            type: 'integer',
            title: 'Total Size Bytes'
        },
        saved_size_bytes: {
            type: 'integer',
            title: 'Saved Size Bytes'
        },
        temporary_size_bytes: {
            type: 'integer',
            title: 'Temporary Size Bytes'
        },
        average_size_bytes: {
            type: 'integer',
            title: 'Average Size Bytes'
        },
        total_size_gb: {
            type: 'number',
            title: 'Total Size Gb'
        },
        saved_size_gb: {
            type: 'number',
            title: 'Saved Size Gb'
        },
        by_type: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'By Type'
        }
    },
    type: 'object',
    required: ['total', 'saved', 'temporary', 'total_size_bytes', 'saved_size_bytes', 'temporary_size_bytes', 'average_size_bytes', 'total_size_gb', 'saved_size_gb', 'by_type'],
    title: 'FileStats'
} as const;

export const FileTypeEnumSchema = {
    type: 'string',
    enum: ['bam', 'beast', 'bed', 'csv', 'docx', 'fasta', 'fastq', 'fastq.gz', 'geojson', 'gff', 'genbank', 'graphml', 'gzip', 'hdf5', 'hs', 'html', 'iqtree', 'jpeg', 'json', 'jsonl', 'log', 'md', 'newick', 'nexus', 'pdb', 'pdf', 'phy', 'text', 'png', 'rmd', 'sam', 'svg', 'tiff', 'toml', 'tsv', 'vega', 'vega-lite', 'vcf', 'vcf.gz', 'xlsx', 'xml', 'yaml', 'zip', 'pair', 'unknown'],
    title: 'FileTypeEnum'
} as const;

export const FileTypeMetadataSchema = {
    properties: {
        extensions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Extensions'
        },
        file_format: {
            type: 'string',
            title: 'File Format'
        },
        mime_types: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Mime Types'
        }
    },
    type: 'object',
    required: ['extensions', 'file_format', 'mime_types'],
    title: 'FileTypeMetadata'
} as const;

export const FilesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FilePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FilesPublic'
} as const;

export const FilesStatisticsSchema = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        },
        total_size: {
            type: 'integer',
            title: 'Total Size'
        }
    },
    type: 'object',
    required: ['count', 'total_size'],
    title: 'FilesStatistics'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const ParamSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        param_type: {
            '$ref': '#/components/schemas/ParamType'
        },
        allowed_file_types: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Allowed File Types'
        },
        multiple: {
            type: 'boolean',
            title: 'Multiple',
            default: false
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        default: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'number'
                },
                {
                    type: 'string'
                },
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default'
        },
        options: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Options'
        },
        required: {
            type: 'boolean',
            title: 'Required',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'param_type'],
    title: 'Param'
} as const;

export const ParamTypeSchema = {
    type: 'string',
    enum: ['str', 'int', 'float', 'bool', 'enum', 'file'],
    title: 'ParamType'
} as const;

export const RunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        tool: {
            '$ref': '#/components/schemas/ToolMinimalPublic'
        },
        params: {
            additionalProperties: true,
            type: 'object',
            title: 'Params'
        },
        status: {
            '$ref': '#/components/schemas/RunStatus'
        },
        shared: {
            type: 'boolean',
            title: 'Shared',
            default: false
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        stdout: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stdout'
        },
        command: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        conda_env_pinned: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conda Env Pinned'
        },
        llm_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Llm Summary'
        },
        files: {
            items: {
                '$ref': '#/components/schemas/FilePublic'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['id', 'tool', 'params', 'status', 'created_at', 'files'],
    title: 'RunPublic'
} as const;

export const RunPublicMinimalSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        tool: {
            '$ref': '#/components/schemas/ToolMinimalPublic'
        },
        params: {
            additionalProperties: true,
            type: 'object',
            title: 'Params'
        },
        status: {
            '$ref': '#/components/schemas/RunStatus'
        },
        shared: {
            type: 'boolean',
            title: 'Shared',
            default: false
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        }
    },
    type: 'object',
    required: ['id', 'tool', 'params', 'status', 'created_at'],
    title: 'RunPublicMinimal'
} as const;

export const RunStatsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        by_status: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'By Status'
        },
        currently_running: {
            type: 'integer',
            title: 'Currently Running'
        },
        success_rate_percent: {
            type: 'number',
            title: 'Success Rate Percent'
        },
        average_runtime_seconds: {
            type: 'integer',
            title: 'Average Runtime Seconds'
        },
        average_runtime_minutes: {
            type: 'number',
            title: 'Average Runtime Minutes'
        },
        last_24_hours: {
            type: 'integer',
            title: 'Last 24 Hours'
        }
    },
    type: 'object',
    required: ['total', 'by_status', 'currently_running', 'success_rate_percent', 'average_runtime_seconds', 'average_runtime_minutes', 'last_24_hours'],
    title: 'RunStats'
} as const;

export const RunStatusSchema = {
    type: 'string',
    enum: ['pending', 'running', 'completed', 'failed', 'cancelled'],
    title: 'RunStatus'
} as const;

export const RunsPublicMinimalSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RunPublicMinimal'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RunsPublicMinimal'
} as const;

export const SetupFileSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['name', 'content'],
    title: 'SetupFile'
} as const;

export const StatsResponseSchema = {
    properties: {
        users: {
            '$ref': '#/components/schemas/SummaryUserStats'
        },
        tools: {
            '$ref': '#/components/schemas/SummaryToolStats'
        },
        runs: {
            '$ref': '#/components/schemas/SummaryRunStats'
        },
        files: {
            '$ref': '#/components/schemas/SummaryFileStats'
        }
    },
    type: 'object',
    required: ['users', 'tools', 'runs', 'files'],
    title: 'StatsResponse'
} as const;

export const SummaryFileStatsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        total_size_gb: {
            type: 'number',
            title: 'Total Size Gb'
        }
    },
    type: 'object',
    required: ['total', 'total_size_gb'],
    title: 'SummaryFileStats'
} as const;

export const SummaryRunStatsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        currently_running: {
            type: 'integer',
            title: 'Currently Running'
        }
    },
    type: 'object',
    required: ['total', 'currently_running'],
    title: 'SummaryRunStats'
} as const;

export const SummaryToolStatsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        enabled: {
            type: 'integer',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['total', 'enabled'],
    title: 'SummaryToolStats'
} as const;

export const SummaryUserStatsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['total'],
    title: 'SummaryUserStats'
} as const;

export const SystemStatsSchema = {
    properties: {
        users: {
            '$ref': '#/components/schemas/UserStats'
        },
        files: {
            '$ref': '#/components/schemas/FileStats'
        },
        runs: {
            '$ref': '#/components/schemas/RunStats'
        },
        tools: {
            '$ref': '#/components/schemas/ToolStats'
        }
    },
    type: 'object',
    required: ['users', 'files', 'runs', 'tools'],
    title: 'SystemStats'
} as const;

export const TargetSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        target_type: {
            type: 'string',
            title: 'Target Type'
        },
        required: {
            type: 'boolean',
            title: 'Required',
            default: true
        }
    },
    type: 'object',
    required: ['path', 'target_type'],
    title: 'Target'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const ToolBadgeSchema = {
    properties: {
        badge: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Badge'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        }
    },
    type: 'object',
    title: 'ToolBadge'
} as const;

export const ToolCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        version: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        explanation_of_results_markdown: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation Of Results Markdown'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        github_repo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Repo'
        },
        docs_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Docs Url'
        },
        paper_doi: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paper Doi'
        },
        license: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'License'
        },
        citation_markdown: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Citation Markdown'
        },
        badges: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ToolBadge'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Badges'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        command: {
            type: 'string',
            title: 'Command'
        },
        conda_env: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CondaEnv'
                },
                {
                    type: 'null'
                }
            ]
        },
        post_install: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Post Install'
        },
        setup_files: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/SetupFile'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Setup Files'
        },
        params: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Param'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Params'
        },
        targets: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Target'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Targets'
        },
        llm_summary_enabled: {
            type: 'boolean',
            title: 'Llm Summary Enabled',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'command'],
    title: 'ToolCreate'
} as const;

export const ToolMinimalPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        params: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Param'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Params'
        },
        favourited: {
            type: 'boolean',
            title: 'Favourited',
            default: false
        },
        favourited_count: {
            type: 'integer',
            title: 'Favourited Count',
            default: 0
        },
        run_count: {
            type: 'integer',
            title: 'Run Count',
            default: 0
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        llm_summary_enabled: {
            type: 'boolean',
            title: 'Llm Summary Enabled',
            default: false
        },
        explanation_of_results_markdown: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation Of Results Markdown'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'ToolMinimalPublic'
} as const;

export const ToolPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        version: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        explanation_of_results_markdown: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation Of Results Markdown'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        github_repo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Repo'
        },
        docs_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Docs Url'
        },
        paper_doi: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paper Doi'
        },
        license: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'License'
        },
        citation_markdown: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Citation Markdown'
        },
        badges: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ToolBadge'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Badges'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        command: {
            type: 'string',
            title: 'Command'
        },
        conda_env: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CondaEnv'
                },
                {
                    type: 'null'
                }
            ]
        },
        post_install: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Post Install'
        },
        setup_files: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/SetupFile'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Setup Files'
        },
        params: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Param'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Params'
        },
        targets: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Target'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Targets'
        },
        llm_summary_enabled: {
            type: 'boolean',
            title: 'Llm Summary Enabled',
            default: false
        },
        favourited: {
            type: 'boolean',
            title: 'Favourited',
            default: false
        },
        status: {
            '$ref': '#/components/schemas/ToolStatus'
        },
        installation_log: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Installation Log'
        },
        favourited_count: {
            type: 'integer',
            title: 'Favourited Count',
            default: 0
        },
        run_count: {
            type: 'integer',
            title: 'Run Count',
            default: 0
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        conda_env_pinned: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conda Env Pinned'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'command', 'status', 'id'],
    title: 'ToolPublic'
} as const;

export const ToolStatsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        enabled: {
            type: 'integer',
            title: 'Enabled'
        },
        disabled: {
            type: 'integer',
            title: 'Disabled'
        },
        by_status: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'By Status'
        },
        most_popular: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Most Popular'
        },
        most_favourited: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Most Favourited'
        }
    },
    type: 'object',
    required: ['total', 'enabled', 'disabled', 'by_status', 'most_popular', 'most_favourited'],
    title: 'ToolStats'
} as const;

export const ToolStatusSchema = {
    type: 'string',
    enum: ['uninstalled', 'uninstalling', 'installed', 'installing', 'failed'],
    title: 'ToolStatus'
} as const;

export const ToolUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        version: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        explanation_of_results_markdown: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation Of Results Markdown'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        github_repo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Repo'
        },
        docs_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Docs Url'
        },
        paper_doi: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paper Doi'
        },
        license: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'License'
        },
        citation_markdown: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Citation Markdown'
        },
        badges: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ToolBadge'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Badges'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        command: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Command'
        },
        conda_env: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CondaEnv'
                },
                {
                    type: 'null'
                }
            ]
        },
        post_install: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Post Install'
        },
        setup_files: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/SetupFile'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Setup Files'
        },
        params: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Param'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Params'
        },
        targets: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Target'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Targets'
        },
        llm_summary_enabled: {
            type: 'boolean',
            title: 'Llm Summary Enabled',
            default: false
        },
        favourited_count: {
            type: 'integer',
            title: 'Favourited Count',
            default: 0
        },
        run_count: {
            type: 'integer',
            title: 'Run Count',
            default: 0
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ToolStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        installation_log: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Installation Log'
        }
    },
    type: 'object',
    title: 'ToolUpdate'
} as const;

export const ToolsOrderBySchema = {
    type: 'string',
    enum: ['created_at', 'run_count'],
    title: 'ToolsOrderBy'
} as const;

export const ToolsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ToolMinimalPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ToolsPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        max_runs: {
            type: 'integer',
            title: 'Max Runs',
            default: 10
        },
        max_storage: {
            type: 'integer',
            title: 'Max Storage',
            default: 26843545600
        },
        max_storage_files: {
            type: 'integer',
            title: 'Max Storage Files',
            default: 300
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        max_runs: {
            type: 'integer',
            title: 'Max Runs',
            default: 10
        },
        max_storage: {
            type: 'integer',
            title: 'Max Storage',
            default: 26843545600
        },
        max_storage_files: {
            type: 'integer',
            title: 'Max Storage Files',
            default: 300
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserStatsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        active: {
            type: 'integer',
            title: 'Active'
        },
        superusers: {
            type: 'integer',
            title: 'Superusers'
        },
        active_last_30_days: {
            type: 'integer',
            title: 'Active Last 30 Days'
        }
    },
    type: 'object',
    required: ['total', 'active', 'superusers', 'active_last_30_days'],
    title: 'UserStats'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        max_runs: {
            type: 'integer',
            title: 'Max Runs',
            default: 10
        },
        max_storage: {
            type: 'integer',
            title: 'Max Storage',
            default: 26843545600
        },
        max_storage_files: {
            type: 'integer',
            title: 'Max Storage Files',
            default: 300
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;