"""setup files and command as string

Revision ID: 07973e937e0e
Revises: e375c0f54d98
Create Date: 2025-01-20 19:10:10.397067

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07973e937e0e'
down_revision = 'e375c0f54d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setupfile',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('tool', 'command',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool', 'command',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_table('setupfile')
    # ### end Alembic commands ###
