"""setup files as JSON

Revision ID: 08447ace0261
Revises: 07973e937e0e
Create Date: 2025-01-20 23:48:49.541229

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08447ace0261'
down_revision = '07973e937e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setupfile')
    op.add_column('tool', sa.Column('setup_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'setup_files')
    op.create_table('setupfile',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name='setupfile_tool_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='setupfile_pkey')
    )
    # ### end Alembic commands ###
