"""add tags to files and runs

Revision ID: 196541e6f1ff
Revises: 4cb61e2ffee2
Create Date: 2025-02-07 11:22:08.937647

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '196541e6f1ff'
down_revision = '4cb61e2ffee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('run', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'tags')
    op.drop_column('file', 'tags')
    # ### end Alembic commands ###
