"""add install log

Revision ID: 4f0add911767
Revises: 88e751b7ff01
Create Date: 2025-01-23 11:31:14.934674

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4f0add911767'
down_revision = '88e751b7ff01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('installation_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'installation_log')
    # ### end Alembic commands ###
