"""remove owner from tool

Revision ID: 561cddce45ed
Revises: 57e037d9da39
Create Date: 2025-01-16 12:15:11.422057

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '561cddce45ed'
down_revision = '57e037d9da39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workflow_owner_id_fkey', 'tool', type_='foreignkey')
    op.drop_column('tool', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('workflow_owner_id_fkey', 'tool', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
