"""llm_summary_enabled per tool

Revision ID: 60c27ce85043
Revises: 7a603344d027
Create Date: 2025-02-25 16:53:53.125481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '60c27ce85043'
down_revision = '7a603344d027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('llm_summary_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('tool', 'llm_summary_template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('llm_summary_template', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tool', 'llm_summary_enabled')
    # ### end Alembic commands ###
