"""add name and discription

Revision ID: 63583522f064
Revises: db7e79b5c888
Create Date: 2025-02-28 13:05:13.440280

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '63583522f064'
down_revision = 'db7e79b5c888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('explanation_of_results_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'explanation_of_results_markdown')
    op.drop_column('run', 'name')
    # ### end Alembic commands ###
