"""add env and tool install status

Revision ID: 641ee630b1dc
Revises: 7c0b89fb2d55
Create Date: 2025-01-22 20:23:06.576056

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '641ee630b1dc'
down_revision = '7c0b89fb2d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE toolstatus AS ENUM ('uninstalled', 'uninstalling', 'installed', 'installing', 'failed')")
    # Drop the 'runstatus' enum type
    
    op.add_column('tool', sa.Column('conda_env', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('post_install', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('status', sa.Enum('uninstalled', 'uninstalling', 'installed', 'installing', 'failed', name='toolstatus'), nullable=True, server_default='uninstalled'))
    op.drop_column('tool', 'setup_command')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('setup_command', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tool', 'status')
    op.drop_column('tool', 'post_install')
    op.drop_column('tool', 'conda_env')
    op.execute("DROP TYPE toolstatus")
    # ### end Alembic commands ###
