"""add conda env pinned

Revision ID: 65229c70a98c
Revises: dc04133f4cf1
Create Date: 2025-02-06 14:38:53.985944

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '65229c70a98c'
down_revision = 'dc04133f4cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('conda_env_pinned', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'conda_env_pinned')
    # ### end Alembic commands ###
