"""add llm comlumns

Revision ID: 7a603344d027
Revises: b2b4757a4d81
Create Date: 2025-02-25 15:22:44.375634

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7a603344d027'
down_revision = 'b2b4757a4d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('llm_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('llm_summary_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'llm_summary_template')
    op.drop_column('run', 'llm_summary')
    # ### end Alembic commands ###
