"""target and params as JSON columns

Revision ID: 7c0b89fb2d55
Revises: 08447ace0261
Create Date: 2025-01-21 00:47:58.357570

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c0b89fb2d55'
down_revision = '08447ace0261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('param')
    op.drop_table('target')
    op.add_column('tool', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tool', sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'targets')
    op.drop_column('tool', 'params')
    op.create_table('target',
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_type', postgresql.ENUM('text', 'image', 'csv', 'tsv', 'json', 'unknown', name='filetype'), autoincrement=False, nullable=True),
    sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name='target_tool_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='target_pkey')
    )
    op.create_table('param',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('param_type', postgresql.ENUM('str', 'int', 'float', 'bool', 'enum', 'file', name='paramtype'), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('default', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('flag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name='param_tool_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='param_pkey')
    )
    # ### end Alembic commands ###
