"""add badges

Revision ID: 85005cd97288
Revises: f984671f2bc2
Create Date: 2025-02-05 18:58:16.080288

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85005cd97288'
down_revision = 'f984671f2bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'badges')
    # ### end Alembic commands ###
