"""conda env as dict

Revision ID: 88e751b7ff01
Revises: 641ee630b1dc
Create Date: 2025-01-22 21:08:30.021830

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88e751b7ff01'
down_revision = '641ee630b1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE tool 
        ALTER COLUMN conda_env 
        TYPE JSONB USING conda_env::jsonb
        """
    )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE tool 
        ALTER COLUMN conda_env 
        TYPE VARCHAR USING conda_env::text
        """
    )
    # ### end Alembic commands ###
