"""Add shared field to Run model

Revision ID: 90a531a74ea9
Revises: 993ca2a5efda
Create Date: 2025-07-02 17:21:34.258130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '90a531a74ea9'
down_revision = '993ca2a5efda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('run', sa.Column('shared', sa.Boolean(), nullable=True))
    # Update existing rows to have shared=False
    op.execute('UPDATE run SET shared = FALSE WHERE shared IS NULL')
    # Now make the column non-nullable
    op.alter_column('run', 'shared', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'shared')
    # ### end Alembic commands ###
