"""add stderr and stdout

Revision ID: 926f7587b4ba
Revises: 6cb0a76c03a7
Create Date: 2024-12-03 23:08:30.544173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '926f7587b4ba'
down_revision = '6cb0a76c03a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('stderr', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('task', sa.Column('stdout', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'stdout')
    op.drop_column('task', 'stderr')
    # ### end Alembic commands ###
