"""file_types

Revision ID: 960daeadc260
Revises: 63583522f064
Create Date: 2025-03-05 17:30:21.504528

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '960daeadc260'
down_revision = '63583522f064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_type',
               existing_type=postgresql.ENUM('text', 'image', 'csv', 'tsv', 'json', 'unknown', name='filetype'),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('text', 'image', 'csv', 'tsv', 'json', 'unknown', name='filetype'),
               nullable=True)
    # ### end Alembic commands ###
