"""add flag to param model

Revision ID: a64cfb1cb333
Revises: 371f0edd6529
Create Date: 2024-05-13 07:55:30.288169

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a64cfb1cb333'
down_revision = '371f0edd6529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('param', sa.Column('flag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('param', 'flag')
    # ### end Alembic commands ###
