"""add more tool metadata

Revision ID: adc08691c909
Revises: 85005cd97288
Create Date: 2025-02-06 10:05:47.582725

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'adc08691c909'
down_revision = '85005cd97288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('github_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('docs_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('paper_doi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('citation_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'citation_markdown')
    op.drop_column('tool', 'license')
    op.drop_column('tool', 'paper_doi')
    op.drop_column('tool', 'docs_url')
    op.drop_column('tool', 'github_repo')
    # ### end Alembic commands ###
