"""add command to task

Revision ID: b21c9f62a313
Revises: 926f7587b4ba
Create Date: 2024-12-04 15:09:11.233997

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b21c9f62a313'
down_revision = '926f7587b4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'command')
    # ### end Alembic commands ###
