"""add useage limits

Revision ID: b2b4757a4d81
Revises: d165d9a90fd0
Create Date: 2025-02-21 14:43:17.499782

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b2b4757a4d81'
down_revision = 'd165d9a90fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('max_runs', sa.Integer(), nullable=False, server_default="10"))
    op.add_column('user', sa.Column('max_storage', sa.BIGINT, nullable=False, server_default="26843545600"))
    op.add_column('user', sa.Column('max_storage_files', sa.Integer(), nullable=False, server_default="1000"))

    # Remove the server default after setting initial values (optional)
    op.alter_column('user', 'max_runs', server_default=None)
    op.alter_column('user', 'max_storage', server_default=None)
    op.alter_column('user', 'max_storage_files', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'max_storage_files')
    op.drop_column('user', 'max_storage')
    op.drop_column('user', 'max_runs')
    # ### end Alembic commands ###
