"""nullable taskiq_id

Revision ID: ba30492b4fe7
Revises: 362680f49514
Create Date: 2024-05-12 15:18:25.128808

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba30492b4fe7'
down_revision = '362680f49514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'taskiq_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'taskiq_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
