"""add input file ids to run internal model

Revision ID: d165d9a90fd0
Revises: 1e03e902ec34
Create Date: 2025-02-12 14:15:31.785641

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd165d9a90fd0'
down_revision = '1e03e902ec34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('input_file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'input_file_ids')
    # ### end Alembic commands ###
