"""add email on complete

Revision ID: db7e79b5c888
Revises: 60c27ce85043
Create Date: 2025-02-26 22:29:45.666761

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'db7e79b5c888'
down_revision = '60c27ce85043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('email_on_completion', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'email_on_completion')
    # ### end Alembic commands ###
