"""add tool version and use that in conda env

Revision ID: dc04133f4cf1
Revises: adc08691c909
Create Date: 2025-02-06 14:09:19.407548

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dc04133f4cf1'
down_revision = 'adc08691c909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'version')
    # ### end Alembic commands ###
