"""add is_group to file

Revision ID: df2765efb999
Revises: 90a531a74ea9
Create Date: 2025-09-27 10:44:02.369448

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'df2765efb999'
down_revision = '90a531a74ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('is_group', sa.Boolean(), nullable=False,
                                      server_default=sa.text('FALSE'),
                                      default=False))
    
    # Convert existing "group" files to use is_group flag
    connection = op.get_bind()
    
    # Update files with file_type = 'group' to have is_group = True and file_type = 'unknown'
    connection.execute(sa.text(
        "UPDATE file SET is_group = true, file_type = 'unknown' WHERE file_type = 'group'"
    ))
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert the file_type changes before dropping the column
    connection = op.get_bind()
    
    # Restore files that were groups back to file_type = 'group'
    connection.execute(sa.text(
        "UPDATE file SET file_type = 'group' WHERE is_group = true AND file_type = 'unknown'"
    ))
    
    op.drop_column('file', 'is_group')
    # ### end Alembic commands ###
