"""files with children

Revision ID: ee0ad060791a
Revises: 944b45f5467a
Create Date: 2025-03-07 13:01:50.607807

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ee0ad060791a'
down_revision = '944b45f5467a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.alter_column('file', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'file', 'file', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.alter_column('file', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('file', 'parent_id')
    # ### end Alembic commands ###
