"""added saved to files

Revision ID: f984671f2bc2
Revises: 4f0add911767
Create Date: 2025-01-23 15:01:07.502752

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f984671f2bc2'
down_revision = '4f0add911767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('saved', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'saved')
    # ### end Alembic commands ###
