/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StreamImport } from './routes/stream'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutRunsIndexImport } from './routes/_layout/runs/index'
import { Route as LayoutFilesIndexImport } from './routes/_layout/files/index'
import { Route as LayoutToolsNameImport } from './routes/_layout/tools/$name'
import { Route as LayoutSearchQueryImport } from './routes/_layout/search/$query'
import { Route as LayoutRunsRunidImport } from './routes/_layout/runs/$runid'

// Create/Update Routes

const StreamRoute = StreamImport.update({
  path: '/stream',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRunsIndexRoute = LayoutRunsIndexImport.update({
  path: '/runs/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFilesIndexRoute = LayoutFilesIndexImport.update({
  path: '/files/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutToolsNameRoute = LayoutToolsNameImport.update({
  path: '/tools/$name',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchQueryRoute = LayoutSearchQueryImport.update({
  path: '/search/$query',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRunsRunidRoute = LayoutRunsRunidImport.update({
  path: '/runs/$runid',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/stream': {
      preLoaderRoute: typeof StreamImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/runs/$runid': {
      preLoaderRoute: typeof LayoutRunsRunidImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/$query': {
      preLoaderRoute: typeof LayoutSearchQueryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/$name': {
      preLoaderRoute: typeof LayoutToolsNameImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/files/': {
      preLoaderRoute: typeof LayoutFilesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/runs/': {
      preLoaderRoute: typeof LayoutRunsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutRunsRunidRoute,
    LayoutSearchQueryRoute,
    LayoutToolsNameRoute,
    LayoutFilesIndexRoute,
    LayoutRunsIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
  StreamRoute,
])

/* prettier-ignore-end */
