/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivateAccountRouteImport } from './routes/activate-account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutRunsIndexRouteImport } from './routes/_layout/runs/index'
import { Route as LayoutFilesIndexRouteImport } from './routes/_layout/files/index'
import { Route as LayoutToolsNameRouteImport } from './routes/_layout/tools/$name'
import { Route as LayoutSearchQueryRouteImport } from './routes/_layout/search/$query'
import { Route as LayoutRunsRunidRouteImport } from './routes/_layout/runs/$runid'
import { Route as LayoutFilesFileIdRouteImport } from './routes/_layout/files/$fileId'

const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateAccountRoute = ActivateAccountRouteImport.update({
  id: '/activate-account',
  path: '/activate-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRunsIndexRoute = LayoutRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilesIndexRoute = LayoutFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsNameRoute = LayoutToolsNameRouteImport.update({
  id: '/tools/$name',
  path: '/tools/$name',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchQueryRoute = LayoutSearchQueryRouteImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRunsRunidRoute = LayoutRunsRunidRouteImport.update({
  id: '/runs/$runid',
  path: '/runs/$runid',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilesFileIdRoute = LayoutFilesFileIdRouteImport.update({
  id: '/files/$fileId',
  path: '/files/$fileId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof AboutRoute
  '/activate-account': typeof ActivateAccountRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stream': typeof StreamRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/files/$fileId': typeof LayoutFilesFileIdRoute
  '/runs/$runid': typeof LayoutRunsRunidRoute
  '/search/$query': typeof LayoutSearchQueryRoute
  '/tools/$name': typeof LayoutToolsNameRoute
  '/files/': typeof LayoutFilesIndexRoute
  '/runs/': typeof LayoutRunsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/activate-account': typeof ActivateAccountRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stream': typeof StreamRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/files/$fileId': typeof LayoutFilesFileIdRoute
  '/runs/$runid': typeof LayoutRunsRunidRoute
  '/search/$query': typeof LayoutSearchQueryRoute
  '/tools/$name': typeof LayoutToolsNameRoute
  '/files': typeof LayoutFilesIndexRoute
  '/runs': typeof LayoutRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/activate-account': typeof ActivateAccountRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stream': typeof StreamRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/files/$fileId': typeof LayoutFilesFileIdRoute
  '/_layout/runs/$runid': typeof LayoutRunsRunidRoute
  '/_layout/search/$query': typeof LayoutSearchQueryRoute
  '/_layout/tools/$name': typeof LayoutToolsNameRoute
  '/_layout/files/': typeof LayoutFilesIndexRoute
  '/_layout/runs/': typeof LayoutRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activate-account'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/stream'
    | '/admin'
    | '/settings'
    | '/files/$fileId'
    | '/runs/$runid'
    | '/search/$query'
    | '/tools/$name'
    | '/files/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/activate-account'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/stream'
    | '/admin'
    | '/settings'
    | '/'
    | '/files/$fileId'
    | '/runs/$runid'
    | '/search/$query'
    | '/tools/$name'
    | '/files'
    | '/runs'
  id:
    | '__root__'
    | '/_layout'
    | '/about'
    | '/activate-account'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/stream'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/files/$fileId'
    | '/_layout/runs/$runid'
    | '/_layout/search/$query'
    | '/_layout/tools/$name'
    | '/_layout/files/'
    | '/_layout/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  ActivateAccountRoute: typeof ActivateAccountRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StreamRoute: typeof StreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate-account': {
      id: '/activate-account'
      path: '/activate-account'
      fullPath: '/activate-account'
      preLoaderRoute: typeof ActivateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runs/': {
      id: '/_layout/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof LayoutRunsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files/': {
      id: '/_layout/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof LayoutFilesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools/$name': {
      id: '/_layout/tools/$name'
      path: '/tools/$name'
      fullPath: '/tools/$name'
      preLoaderRoute: typeof LayoutToolsNameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search/$query': {
      id: '/_layout/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof LayoutSearchQueryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runs/$runid': {
      id: '/_layout/runs/$runid'
      path: '/runs/$runid'
      fullPath: '/runs/$runid'
      preLoaderRoute: typeof LayoutRunsRunidRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files/$fileId': {
      id: '/_layout/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof LayoutFilesFileIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFilesFileIdRoute: typeof LayoutFilesFileIdRoute
  LayoutRunsRunidRoute: typeof LayoutRunsRunidRoute
  LayoutSearchQueryRoute: typeof LayoutSearchQueryRoute
  LayoutToolsNameRoute: typeof LayoutToolsNameRoute
  LayoutFilesIndexRoute: typeof LayoutFilesIndexRoute
  LayoutRunsIndexRoute: typeof LayoutRunsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFilesFileIdRoute: LayoutFilesFileIdRoute,
  LayoutRunsRunidRoute: LayoutRunsRunidRoute,
  LayoutSearchQueryRoute: LayoutSearchQueryRoute,
  LayoutToolsNameRoute: LayoutToolsNameRoute,
  LayoutFilesIndexRoute: LayoutFilesIndexRoute,
  LayoutRunsIndexRoute: LayoutRunsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  ActivateAccountRoute: ActivateAccountRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StreamRoute: StreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
